version: '3.8'

services:
  api:
    container_name: bdda_api
    build: .
    command: sh -c 'yoyo list --database postgresql://postgres:postgres@postgreSQL/postgres; yoyo apply --database postgresql://postgres:postgres@postgreSQL/postgres --batch; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgreSQL
      POSTGRES_PORT: 5432
  postgreSQL:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  postgres_data: