name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test base de dades columnars
      id: test-base-de-dades-columnars
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test base de dades columnars
        setup-command: docker-compose up -d
        command: docker exec bdda_api sh -c "pytest"
        timeout: 10
        max-score: 13
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-BASE-DE-DADES-COLUMNARS_RESULTS: "${{steps.test-base-de-dades-columnars.outputs.result}}"
      with:
        runners: test-base-de-dades-columnars
